### PR TITLE
Add support for rectangles and grids

### PR DESCRIPTION
**Pull request by alexpana**
This was requested by Casey Muratori in a handmade hero video, and I had a little spare time.

https://youtu.be/Yu8k7a1hQuU?t=3380

### CODE REVIEW

**Comment by alexpana** [comment]
I also recorded myself fumbling thorugh the code for the first time and implementing the PR: https://www.youtube.com/watch?v=Kfx1MrE6s8Q

**Comment by serge-rgb** [comment]
Hey, 

Thanks for doing this,
Just one thing. Rectangles should probably work with rotation so that the sides are always parallel to the screen. Currently this feature generates rotated triangles when the view is rotated. Would you be willing to implement this on top of what you have already done?

**Comment by alexpana** [comment]
Hello,

Thanks for the response. I don't have much experience using milton so I didn't take into account all the ways it could be used.

I'll try to have a look at it this week.

**Comment by serge-rgb** [comment]
No worries, it's an easy thing to miss. Otherwise, it looks like a good
change.

Thanks a lot! Let me know if I can help

-Sergio

**Pull request merged**
