### PR TITLE
macOS build fixes and issues

### PR DESCRIPTION
**Pull request by kainjow**
Fixed some issues compiling the Mac version. Didn't yet try configuring the Tundra build file, but [CMake](https://cmake.org) could be used as an alternative/addition where a macOS bundle and dmg can be created very easily (and easy to generate an Xcode project).

Anyways, the program won't run though, I get this:

```
$ ./build/milton
Running Milton
Initializing SDL... Done.
Loading preferences... Could not open file for writing prefs
Done.
Creating Milton Window
Created OpenGL context with version 2.1 INTEL-10.20.23
    and GLSL 1.20
GL_INVALID_ENUM in: /Users/kainjow/Projects/milton/src/gl_helpers.cc:93
   ---- Expression: glGetIntegerv(GL_NUM_EXTENSIONS, (GLint*)&num_extensions)
Maximum viewport dimensions, 16384.000000x16384.000000
Vendor string: "Intel Inc."
Increased guid to 1
GL_INVALID_OPERATION in: /Users/kainjow/Projects/milton/src/hardware_renderer.cc:299
   ---- Expression: glBufferData(GL_ARRAY_BUFFER, array_count(data)*sizeof(*data), data, GL_DYNAMIC_DRAW)
GL_INVALID_OPERATION in: ../src/../third_party/imgui/imgui_impl_sdl_gl3.cpp:85
   ---- Expression: glBindVertexArray(g_VaoHandle)
GL_INVALID_OPERATION in: ../src/../third_party/imgui/imgui_impl_sdl_gl3.cpp:126
   ---- Expression: glViewport(last_viewport[0], last_viewport[1], (GLsizei)last_viewport[2], (GLsizei)last_viewport[3])
GL_INVALID_OPERATION in: ../src/../third_party/imgui/imgui_impl_sdl_gl3.cpp:85
   ---- Expression: glBindVertexArray(g_VaoHandle)
GL_INVALID_OPERATION in: ../src/../third_party/imgui/imgui_impl_sdl_gl3.cpp:126
   ---- Expression: glViewport(last_viewport[0], last_viewport[1], (GLsizei)last_viewport[2], (GLsizei)last_viewport[3])
Could not open file for writing prefs :(
```

From a quick google if I add this near the top of `third_party/Fxaa3_11.f.glsl` it will run and I can do some basic painting, but it gets very glitchy soon and starts showing tons of error on repaint (or whenever the mouse moves):

    #extension GL_EXT_gpu_shader4 : enable

Here's the new output:

```
$ ./build/milton
Running Milton
Initializing SDL... Done.
Loading preferences... Could not open file for writing prefs
Done.
Creating Milton Window
Created OpenGL context with version 2.1 INTEL-10.20.23
    and GLSL 1.20
GL_INVALID_ENUM in: /Users/kainjow/Projects/milton/src/gl_helpers.cc:93
   ---- Expression: glGetIntegerv(GL_NUM_EXTENSIONS, (GLint*)&num_extensions)
Maximum viewport dimensions, 16384.000000x16384.000000
Vendor string: "Intel Inc."
Increased guid to 1
GL_INVALID_OPERATION in: /Users/kainjow/Projects/milton/src/hardware_renderer.cc:299
   ---- Expression: glBufferData(GL_ARRAY_BUFFER, array_count(data)*sizeof(*data), data, GL_DYNAMIC_DRAW)
GL_INVALID_OPERATION in: ../src/../third_party/imgui/imgui_impl_sdl_gl3.cpp:85
   ---- Expression: glBindVertexArray(g_VaoHandle)
```

### CODE REVIEW

**Comment by serge-rgb** [comment]
Thanks! 
I believe tundra has an easy way to generate Bundles, but we'll see...
I will see if I can replicate the glBufferData/glBindVertexArray problem with my macbook
Also, I'll add you to the credits in the next commit

**Comment by kainjow** [comment]
Yes, I see now that there is bundle support. Just had to find my way around Tundra. I am also [working](https://github.com/Homebrew/homebrew-core/pull/9172) on adding Tundra to [Homebrew](http://brew.sh) so it'll be easier to install.

**Comment by kainjow** [comment]
If you can get the OpenGL stuff working, I can implement fairly easily the missing platform functions for macOS (would need to covert the file to Objective-C).

**Comment by serge-rgb** [comment]
That would be great! I'll get back to you after fixing the GL problems

**Pull request merged**
